# Generated by Django 3.0.4 on 2020-03-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='favTracks',
        ),
        migrations.RemoveField(
            model_name='album',
            name='trackList',
        ),
    ]
