# Generated by Django 3.0.4 on 2020-03-23 23:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200323_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favTracks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None),
        ),
        migrations.AddField(
            model_name='album',
            name='trackList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None),
        ),
    ]
