# Generated by Django 3.0.4 on 2020-03-24 04:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('foodType', models.CharField(max_length=150)),
                ('picture', models.CharField(max_length=250)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None)),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
